CREATE DATABASE "TriplePlay" ENCODING 'UTF-8';

CREATE ROLE "TriplePlay";

ALTER ROLE "TriplePlay" NOSUPERUSER;
ALTER ROLE "TriplePlay" NOCREATEDB;
ALTER ROLE "TriplePlay" NOCREATEUSER;
ALTER ROLE "TriplePlay" NOCREATEROLE;
ALTER ROLE "TriplePlay" LOGIN;
