#!/usr/bin/env bash
echo -n "Introduzca la nueva clave para la conexión a la base de datos: " 1>&2
if read -s pw; then
        printf "ALTER USER \"TriplePlay\" ENCRYPTED PASSWORD '%s'" "$pw" | psql -f - &> /dev/null
        printf '<?php define("TRIPLEPLAY_PSQL_PASSWORD", "%s"); ?>\n' "$pw" > ../webroot/password.php
        echo 1>&2
fi
