#!/usr/bin/env bash

function ask_pw() {
        if [[ $# != 3 ]]
        then
                printf '%s: número incorrecto de argumentos\n' "$FUNCNAME"
                return -1
        fi

        if read -s pw
        then
                printf "ALTER USER \"${3//\"/\"\"}\" LOGIN ENCRYPTED PASSWORD '%s'\n" "${pw//\'/''}" | psql -f - &> /dev/null
                printf "<?php define('${1^^}_${2^^}_PSQL_PASSWORD', '%s'); ?>\n" "${pw//\'/\'}" > "/var/www/$1/include/password/$2.php"
                echo 1>&2
        else
                printf '\nwarning: no password defined for role %s\n' "$3" 1>&2
        fi
}

echo -n "Introduzca la nueva clave para la conexión a la base de datos de la autenticación del sistema Fantasy: " 1>&2
ask_pw 'Fantasy' 'auth'  'Fantasy (autenticación)'

echo -n "Introduzca la nueva clave para la conexión a la base de datos de los usuarios normales del sistema Fantasy: " 1>&2
ask_pw 'Fantasy' 'user'  'Fantasy (usuario normal)'

echo -n "Introduzca la nueva clave para la conexión a la base de datos de los usuarios administradores del sistema Fantasy: " 1>&2
ask_pw 'Fantasy' 'admin' 'Fantasy (administrador)'

echo -n "Introduzca la nueva clave para la conexión a la base de datos de los usuarios sin registrar del sistema Fantasy: " 1>&2
ask_pw 'Fantasy' 'guest' 'Fantasy (visitante)'
