#!/usr/bin/env bash
echo -n "Introduzca la nueva clave para la conexión a la base de datos: " 1>&2
if read -s pw; then
        epw="${pw//\'/\'}"
        printf 'ALTER USER "Fantasy" LOGIN ENCRYPTED PASSWORD '\''%s'\' "$epw" | psql -f - &> /dev/null
        printf '<?php define("FANTASY_PSQL_PASSWORD", '\''%s'\''); ?>\n' "$epw" > /var/www/Fantasy/password.php
        echo 1>&2
fi
