#!/usr/bin/env bash
echo -n "Introduzca la nueva clave para la conexión a la base de datos: " 1>&2
if read -s pw; then
        epw="${pw//\'/\'}"
        printf 'ALTER USER "TriplePlay" ENCRYPTED PASSWORD '\''%s'\' "$epw" | psql -f - &> /dev/null
        printf '<?php define("TRIPLEPLAY_PSQL_PASSWORD", '\''%s'\''); ?>\n' "$epw" > /var/www/TriplePlay/password.php
        echo 1>&2
fi
