CREATE DATABASE "Baseball" ENCODING 'UTF-8';

CREATE ROLE "Baseball" LOGIN;

ALTER ROLE "Baseball" NOSUPERUSER;
ALTER ROLE "Baseball" NOCREATEDB;
ALTER ROLE "Baseball" NOCREATEUSER;
ALTER ROLE "Baseball" NOCREATEROLE;
