setup:
	psql -f setup.sql

delete:
	psql -f delete.sql "Baseball"

truncate:
	psql -f truncate.sql "Baseball"

drop:
	psql -f drop.sql "Baseball"

load:
	psql -f load.sql "Baseball"

perms:
	psql -f perms.sql "Baseball"

sample:
	psql -f sample.sql "Baseball"

schema:
	psql -f schema.sql "Baseball"

