CREATE ROLE "Fantasy (autenticación)"  NOLOGIN NOSUPERUSER NOCREATEDB NOCREATEROLE;
CREATE ROLE "Fantasy (usuario normal)" NOLOGIN NOSUPERUSER NOCREATEDB NOCREATEROLE;
CREATE ROLE "Fantasy (administrador)"  NOLOGIN NOSUPERUSER NOCREATEDB NOCREATEROLE IN ROLE "Fantasy (usuario normal)";
