TRUNCATE
        "Fantasy"."Usuario",
        "Fantasy"."Manager",
        "Fantasy"."Administrador",
        "Fantasy"."passwd",
        "Fantasy"."Liga",
        "Fantasy"."Participa",
        "Fantasy"."Jugador",
        "Fantasy"."Peso",
        "Fantasy"."Altura",
        "Fantasy"."Roster",
        "Fantasy"."Contenido de roster",
        "Fantasy"."Estadística de bateo",
        "Fantasy"."Estadística de pitcheo",
        "Fantasy"."Juega",
        "Fantasy"."Juego",
        "Fantasy"."Noticia";
