CREATE USER "Fantasy (autenticación)"  NOLOGIN NOSUPERUSER NOCREATEDB NOCREATEROLE;
CREATE USER "Fantasy (usuario normal)" NOLOGIN NOSUPERUSER NOCREATEDB NOCREATEROLE;
CREATE USER "Fantasy (administrador)"  NOLOGIN NOSUPERUSER NOCREATEDB NOCREATEROLE IN ROLE "Fantasy (usuario normal)";
